feat: add accordion

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,14 +5,14 @@ approved="\033[1;32m√"
 fixer="\033[1;31m×"
 reset="\033[0m"
 
-# echo "${warning} Iniciando build...${reset}"
+echo "${warning} Iniciando build...${reset}"
 
-# echo 'Verificando exports... ' &&
-# node scripts/generate-exports.js &&
+echo 'Verificando exports... ' &&
+node scripts/generate-exports.js &&
 
-# if npm run build; then
-#   echo "${approved} Build finalizada com sucesso! Conferir resultado.${reset}"
-# else
-#   echo "${fixer} Build falhou! Abortando push.${reset}"
-#   exit 1
-# fi
+if npm run build; then
+  echo "${approved} Build finalizada com sucesso! Conferir resultado.${reset}"
+else
+  echo "${fixer} Build falhou! Abortando push.${reset}"
+  exit 1
+fi
